container:
  image: ubuntu:24.04
  cpu: 8
  memory: 32G
  volumes:
    - /home/cirrus:/home/cirrus

build_job:
  timeout_in: 120m
  environment:
    CIRRUS_CLONE_DEPTH: 1
  
  install_dependencies_script:
    - apt-get update
    - apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-21-jdk python3 python-is-python3
    - mkdir -p ~/bin
    - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    - chmod a+x ~/bin/repo

  sync_script:
    - export PATH="$HOME/bin:$PATH"
    - git config --global user.email "cloud-build@infinity.org"
    - git config --global user.name "CloudBuilder"
    - mkdir -p /home/cirrus/android && cd /home/cirrus/android
    - repo init -u https://github.com/ProjectInfinity-X/manifest.git -b 16 --git-lfs --depth=1
    - git clone https://github.com/DaniHasReal/android_device_samsung_a04.git -b lineage_22 device/samsung/a04
    - git clone https://github.com/DaniHasReal/android_vendor_samsung_a04.git -b main vendor/samsung/a04
    - git clone https://github.com/DaniTheSillyFem/kernel_samsung_a04.git -b linux-4.19.y kernel/samsung/a04
    - repo sync -c --force-sync --no-clone-bundle --no-tags --optimized-fetch --prune -j$(nproc --all)

  build_script:
    - export PATH="$HOME/bin:$PATH"
    - cd /home/cirrus/android
    - source build/envsetup.sh
    - lunch infinity_a04-userdebug
    - mka bacon -j$(nproc --all)
# start build
